# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2
#bundle exec jekyll serve

# Personal info
name: Lukas Lee 
title: Estudiando soluciones de Conectividad y Redes
#email: lukas@lleen.tech
website: 

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: siguemen
github_username:  skoll43
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: lukas-lee
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: <i class="fas fa-address-card"></i> Acerca de mi
about_profile_image: images/cv.jpg
about_content: | # this will include new lines to allow paragraphs
  Estoy en internet! Actualmente curso el segundo año de Ing en Conectividad y redes.

  Me preparo para la certificacion <mark>CCNA</mark> 

content:
  - title: Experiencia # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Independiente
        link: 
        # link_text: boringcompany.com
        sub_title: Soporte computacional
        caption: 2020
        quote: >
          Prestacion de soporte a <mark>Windows</mark> y <mark>Android</mark> a usuarios
        description: | # this will include new lines to allow paragraphs
          

  - title: Cursos # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Coursera | Grow with <i class="fab fa-google"></i>
        caption: 2020 
        sub_title: Google IT Support
        quote: >
          El certificado de cinco cursos, desarrollado por los empleados de Google, incluye un plan de estudios relevante para la industria diseñado para prepararlo para un puesto de nivel de entrada en el soporte de TI. trabajo de mesa de ayuda en persona o remota, ya sea en pequeñas tiendas o en una empresa global, como Google.
        description: | # this will include new lines to allow paragraphs
          Entrenamiento en soporte informático, introducción de enrutado y redes, conceptos de informática computacional, powershell/bash básico, administración de infraestructuras pequeñas y conceptos básicos de implementaciones de seguridad
          
          - <a href="https://www.coursera.org/account/accomplishments/professional-cert/VDX2PGZBALPT?utm_source=link&utm_medium=certificate&utm_content=cert_image&utm_campaign=sharing_cta&utm_product=prof">Certificado</a>
        
      - layout: left
        title: Cisco Networking Academy
        caption: 2020 
        sub_title: Cursos
        quote: >
          Mediante cursos en Duoc
        description: | # this will include new lines to allow paragraphs
          - <a href="https://www.linkedin.com/in/lukas-lee/detail/treasury/education:700823951/?entityUrn=urn%3Ali%3Afsd_profileTreasuryMedia%3A(ACoAAC1LxrgBbpZLf0unhyD3wLE__TxoQwlNqRE%2C1611157249487)&section=education%3A700823951&treasuryCount=2">Introducción a IoT de Cisco Networking Academy®</a>
          
          - <a href="https://www.linkedin.com/in/lukas-lee/detail/treasury/education:700823951/?entityUrn=urn%3Ali%3Afsd_profileTreasuryMedia%3A(ACoAAC1LxrgBbpZLf0unhyD3wLE__TxoQwlNqRE%2C1611157558878)&section=education%3A700823951&treasuryCount=2)">Cybersecurity Essentials Cisco Networking Academy®</a>


  - title: Estudios # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: <span style="color:#DAA520">Duoc</span> <span style="color:MidnightBlue">UC </span>
        caption: 2020 - Actualidad
        sub_title: Conectividad y Redes
        quote: >
         Realizar o controlar labores de Soporte Computacional y de Infraestructura de Redes, diseñar soluciones de conectividad utilizando las tendencias tecnológicas, gestionar proyectos de redes y telecomunicaciones.
        description: | # this will include new lines to allow paragraphs


  - title: Proyectos # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Pronto
        link: github.com/skoll43
        # link_text: Project Website
        additional_links:
          - title:  github.com/skoll43
            icon: fab fa-github
            url: github.com/skoll43
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          
        description: | # this will include new lines to allow paragraphs

#  - title: En mi tiempo libre
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Entre otros de mis intereses y hobbies estan:
 #     - Gaming
 #     - Caminar por deporte jaja
#      - Saturar esta web
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

#       #<i class="fas fa-code"></i><a href="https://github.com/sproogen/modern-resume-theme">~~Inspirarse en plantillas~~</a>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
